# Data Import

In [6]:
import numpy as np
import pandas as pd

In [12]:
data = pd.read_csv(r"C:\Users\JOHN\Desktop\Messy data set.csv")
print(data)

     ID     Name         Age               Email    JoinDate    Salary
0     1    Alice          25   alice@example.com    1/1/2020     50000
1     2      Bob          30     bob@example.com  not a date     60000
2     2      Bob          30     bob@example.com    2/1/2020     60000
3     4  Charlie         NaN            charlie@    3/1/2020     70000
4     5    David  Twenty-two                 NaN    4/1/2020       NaN
5     6      Eve          45         eve@example    5/1/2020     90000
6     7    Frank          50  frank@@example.com    6/1/2020    100000
7     8    Grace          55   grace@example.com    1/7/2020  one lakh
8  nine    Heidi          60   heidi@example.com  2020.08.01    120000
9    10      NaN          65      10@example.com    9/1/2020    130000

# Identifying Missing Value

In [15]:
missing_data = data.isnull().sum()
print('Missing_data:')
missing_data

Missing_data:

ID          0
Name        1
Age         1
Email       1
JoinDate    0
Salary      1
dtype: int64

# Checking DataTypes

In [18]:
data.dtypes

ID          object
Name        object
Age         object
Email       object
JoinDate    object
Salary      object
dtype: object

# Assigning DataTypes

In [21]:
data = data.replace('Twenty-two',22)

In [23]:
data['Age'] = data['Age'].astype(float)

In [25]:
data = data.replace('one lakh',100000)

In [27]:
data['Salary'] = data['Salary'].astype(float)

In [29]:
data

     ID     Name   Age               Email    JoinDate    Salary
0     1    Alice  25.0   alice@example.com    1/1/2020   50000.0
1     2      Bob  30.0     bob@example.com  not a date   60000.0
2     2      Bob  30.0     bob@example.com    2/1/2020   60000.0
3     4  Charlie   NaN            charlie@    3/1/2020   70000.0
4     5    David  22.0                 NaN    4/1/2020       NaN
5     6      Eve  45.0         eve@example    5/1/2020   90000.0
6     7    Frank  50.0  frank@@example.com    6/1/2020  100000.0
7     8    Grace  55.0   grace@example.com    1/7/2020  100000.0
8  nine    Heidi  60.0   heidi@example.com  2020.08.01  120000.0
9    10      NaN  65.0      10@example.com    9/1/2020  130000.0

In [31]:
data = data.replace('not a date',"NaN")

In [33]:
data = data.replace('2020.08.01',"NaN")

# Imputing Missing Value

In [36]:
# Import SimpleImputer

In [38]:
from sklearn.impute import SimpleImputer

In [40]:
imputer = SimpleImputer(strategy = 'mean')
imputer.fit(data[['Age']])
data[['Age']] = imputer.transform(data[['Age']])

In [42]:
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit(data[['JoinDate']])
data[['JoinDate']] = imputer.transform(data[['JoinDate']])

In [44]:
imputer = SimpleImputer(strategy = 'most_frequent')
imputer.fit(data[['Email']])
data [['Email']] = imputer.transform(data[['Email']])

In [46]:
imputer = SimpleImputer(strategy = 'most_frequent')
imputer.fit(data[['Name']])
data [['Name']] = imputer.transform(data[['Name']])

In [48]:
data = data.replace('nine',9)

In [50]:
imputer = SimpleImputer(strategy='mean')
imputer.fit(data[['Salary']])
data[['Salary']] = imputer.transform(data[['Salary']])

In [52]:
data

   ID     Name        Age               Email  JoinDate         Salary
0   1    Alice  25.000000   alice@example.com  1/1/2020   50000.000000
1   2      Bob  30.000000     bob@example.com       NaN   60000.000000
2   2      Bob  30.000000     bob@example.com  2/1/2020   60000.000000
3   4  Charlie  42.444444            charlie@  3/1/2020   70000.000000
4   5    David  22.000000     bob@example.com  4/1/2020   86666.666667
5   6      Eve  45.000000         eve@example  5/1/2020   90000.000000
6   7    Frank  50.000000  frank@@example.com  6/1/2020  100000.000000
7   8    Grace  55.000000   grace@example.com  1/7/2020  100000.000000
8   9    Heidi  60.000000   heidi@example.com       NaN  120000.000000
9  10      Bob  65.000000      10@example.com  9/1/2020  130000.000000

In [54]:
data.dtypes

ID           object
Name         object
Age         float64
Email        object
JoinDate     object
Salary      float64
dtype: object

In [56]:
# Assigning Datatypes
data['JoinDate'] = pd.to_datetime(data['JoinDate'])

In [58]:
data.dtypes

ID                  object
Name                object
Age                float64
Email               object
JoinDate    datetime64[ns]
Salary             float64
dtype: object

In [60]:
# Applying Filter_warning
import warnings
warnings.filterwarnings('ignore')

In [62]:
data['JoinDate'] = data['JoinDate'].fillna(method="ffill")

In [64]:
data

   ID     Name        Age               Email   JoinDate         Salary
0   1    Alice  25.000000   alice@example.com 2020-01-01   50000.000000
1   2      Bob  30.000000     bob@example.com 2020-01-01   60000.000000
2   2      Bob  30.000000     bob@example.com 2020-02-01   60000.000000
3   4  Charlie  42.444444            charlie@ 2020-03-01   70000.000000
4   5    David  22.000000     bob@example.com 2020-04-01   86666.666667
5   6      Eve  45.000000         eve@example 2020-05-01   90000.000000
6   7    Frank  50.000000  frank@@example.com 2020-06-01  100000.000000
7   8    Grace  55.000000   grace@example.com 2020-01-07  100000.000000
8   9    Heidi  60.000000   heidi@example.com 2020-01-07  120000.000000
9  10      Bob  65.000000      10@example.com 2020-09-01  130000.000000

# Removing Inconsistent Value

In [67]:
unique_value = data['ID'].unique()
unique_value

array(['1', '2', '4', '5', '6', '7', '8', 9, '10'], dtype=object)

In [69]:
unique_value = data['Email'].unique()
unique_value

array(['alice@example.com', 'bob@example.com', 'charlie@', 'eve@example',
       'frank@@example.com', 'grace@example.com', 'heidi@example.com',
       '10@example.com'], dtype=object)

# Dealing With Duplicate Value

In [72]:
duplicates = data.duplicated()
data[duplicates]

Empty DataFrame
Columns: [ID, Name, Age, Email, JoinDate, Salary]
Index: []

In [74]:
duplicates = data.duplicated()
duplicates

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool