# 1.Import Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv(r"C:\Users\JOHN\Desktop\Messy data set.csv")

In [4]:
print(data)

     ID     Name         Age               Email    JoinDate    Salary
0     1    Alice          25   alice@example.com    1/1/2020     50000
1     2      Bob          30     bob@example.com  not a date     60000
2     2      Bob          30     bob@example.com    2/1/2020     60000
3     4  Charlie         NaN            charlie@    3/1/2020     70000
4     5    David  Twenty-two                 NaN    4/1/2020       NaN
5     6      Eve          45         eve@example    5/1/2020     90000
6     7    Frank          50  frank@@example.com    6/1/2020    100000
7     8    Grace          55   grace@example.com    1/7/2020  one lakh
8  nine    Heidi          60   heidi@example.com  2020.08.01    120000
9    10      NaN          65      10@example.com    9/1/2020    130000

In [5]:
data.head(10)

     ID     Name         Age               Email    JoinDate    Salary
0     1    Alice          25   alice@example.com    1/1/2020     50000
1     2      Bob          30     bob@example.com  not a date     60000
2     2      Bob          30     bob@example.com    2/1/2020     60000
3     4  Charlie         NaN            charlie@    3/1/2020     70000
4     5    David  Twenty-two                 NaN    4/1/2020       NaN
5     6      Eve          45         eve@example    5/1/2020     90000
6     7    Frank          50  frank@@example.com    6/1/2020    100000
7     8    Grace          55   grace@example.com    1/7/2020  one lakh
8  nine    Heidi          60   heidi@example.com  2020.08.01    120000
9    10      NaN          65      10@example.com    9/1/2020    130000

# 2.Identify Missing Value

In [7]:
data.isnull()

      ID   Name    Age  Email  JoinDate  Salary
0  False  False  False  False     False   False
1  False  False  False  False     False   False
2  False  False  False  False     False   False
3  False  False   True  False     False   False
4  False  False  False   True     False    True
5  False  False  False  False     False   False
6  False  False  False  False     False   False
7  False  False  False  False     False   False
8  False  False  False  False     False   False
9  False   True  False  False     False   False

In [8]:
data.isnull().sum()

ID          0
Name        1
Age         1
Email       1
JoinDate    0
Salary      1
dtype: int64

# 3.Imputing Missing Data

In [10]:
missing_data = data.isnull().sum()
print("Missing Data:")
missing_data

Missing Data:

ID          0
Name        1
Age         1
Email       1
JoinDate    0
Salary      1
dtype: int64

# Imputing Missing Value

In [12]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Sample data with a missing value
data = pd.DataFrame({
    'ID': [10, 15, None, 20, 25]
})

# Create the imputer with mean strategy
imputer = SimpleImputer(strategy='mean')

# Fit the imputer and transform the data
imputer.fit(data[['ID']])
data[['ID']] = imputer.transform(data[['ID']])

# Show the result
print(data)

     ID
0  10.0
1  15.0
2  17.5
3  20.0
4  25.0

In [13]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Sample data with a missing value
data = pd.DataFrame({
    'Age': [35, 45, 25,None, 20, 25]
})

# Create the imputer with mean strategy
imputer = SimpleImputer(strategy='mean')

# Fit the imputer and transform the data
imputer.fit(data[['Age']])
data[['Age']] = imputer.transform(data[['Age']])

# Show the result
print(data)

    Age
0  35.0
1  45.0
2  25.0
3  30.0
4  20.0
5  25.0

# 4.Checking Data Types

In [15]:
print(data.dtypes)

Age    float64
dtype: object

# 5.Removing Inconsistent Value

In [17]:
unique_values = data['Age'].unique()
unique_values

array([35., 45., 25., 30., 20.])

In [18]:
import pandas as pd

data = pd.DataFrame({'ID': ['51', '25', 'inconsistent_value', '54']})
data = data[data['ID'] != 'inconsistent_value']

print(data)

   ID
0  51
1  25
3  54

# 6.Assiging Data Type

In [20]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'age': [25, 30]
}, dtype='object')
print(df)

    name age
0  Alice  25
1    Bob  30

In [21]:
import pandas as pd

data = pd.DataFrame({
    'age': ['25', '30', '35']
})

data['age'] = data['age'].astype(int)
print(data.dtypes)

age    int32
dtype: object

# 7.Dealing With Duplicate

In [23]:
import pandas as pd

data = pd.DataFrame({
    'name': ['Ram', 'Shyam', 'Sita', 'Sita', 'Ram'],
    'age': [35, 30, 25, 25, 35]
})

duplicates = data.duplicated()
print(data[duplicates])

   name  age
3  Sita   25
4   Ram   35

# 8.Sorting Data

In [25]:
data.sort_values(by='age', ascending=True)  # Ascending order
data.sort_values(by='age', ascending=False) # Descending order

    name  age
0    Ram   35
4    Ram   35
1  Shyam   30
2   Sita   25
3   Sita   25

# 9.Boolean Filtering

In [27]:
filtered_data = data[data['age'] > 25]
print(filtered_data)

    name  age
0    Ram   35
1  Shyam   30
4    Ram   35

# 11.Is, In

In [29]:
import pandas as pd

data = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 22, 28]
})

# Filter rows where name is either 'Alice' or 'David'
filtered_data = data[data['name'].isin(['Alice', 'David'])]

print(filtered_data)

    name  age
0  Alice   25
3  David   28

# 12.Loc And i Loc

In [31]:
import pandas as pd

data = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 22]
}, index=['a', 'b', 'c'])

In [32]:
data.loc['a']       
data.loc[:, 'age']

a    25
b    30
c    22
Name: age, dtype: int64

In [33]:
subset = data.iloc[1:3, 0:2]

print(subset)

      name  age
b      Bob   30
c  Charlie   22

# 13.Combining & Conditions

In [35]:
import pandas as pd

data = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 22, 28],
    'salary' :[10000,20000,30000,40000]
})
## OR Condition
filtered_data = data[(data['age'] > 25) | (data['salary'] < 50000)]
filtered_data

      name  age  salary
0    Alice   25   10000
1      Bob   30   20000
2  Charlie   22   30000
3    David   28   40000

In [36]:
## AND Condition
filtered_data = data[(data['age'] > 25) & (data['salary'] < 50000)]
filtered_data

    name  age  salary
1    Bob   30   20000
3  David   28   40000

In [37]:

# Filter: name starts with 'A' AND age is less than 30
filtered_data = data[(data['name'].str.startswith('A')) & (data['age'] < 30)]
print(filtered_data)

    name  age  salary
0  Alice   25   10000

# 14.Joining Data

In [39]:
import pandas as pd

# First DataFrame
data1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

# Second DataFrame
data2 = pd.DataFrame({
    'ID': [3, 4, 5, 6],
    'Score': [85, 92, 78, 88]
})
inner_join = pd.merge(data1, data2, on='ID', how='inner')
print(inner_join)

   ID     Name  Score
0   3  Charlie     85
1   4    David     92

# 15.Concatenating Data

In [41]:
import pandas as pd

# First DataFrame
data1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['Alice', 'Bob']
})

# Second DataFrame (same columns as data1)
data2 = pd.DataFrame({
    'ID': [3, 4],
    'Name': ['Charlie', 'David']
})

# Concatenate vertically
concatenated_data = pd.concat([data1, data2])

# Display result
print(concatenated_data.head())

   ID     Name
0   1    Alice
1   2      Bob
0   3  Charlie
1   4    David

# 16.Count Value

In [43]:
import pandas as pd
# Simple Dataframe
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})
# Count Values
counts =data['Name'].value_counts()
print(counts)

Name
Alice      1
Bob        1
Charlie    1
David      1
Name: count, dtype: int64

In [44]:
import pandas as pd
# Simple Dataframe
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David','Alice', 'Bob', 'Charlie', 'David']
})
# Count Values
counts =data['Name'].value_counts()
print(counts)

Name
Alice      2
Bob        2
Charlie    2
David      2
Name: count, dtype: int64

# 17.Descriptive

In [46]:
data.describe()

         Name
count       8
unique      4
top     Alice
freq        2

# 18.Group By

In [48]:
import pandas as pd

# Dataframe
data = pd.DataFrame({
    'ID' : [1,2,3,4,5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David','Eve']
})
# Group by
Grouped = data.groupby('Name')['ID'].mean()

print(Grouped)

Name
Alice      1.0
Bob        2.0
Charlie    3.0
David      4.0
Eve        5.0
Name: ID, dtype: float64

# 19.Pivot Table

In [50]:
import pandas as pd

# Sample data
data = pd.DataFrame({
    'ID' : [1,2,3,4,5],
    'Age' : [20,25,30,35,40],
    'Name': ['Alice', 'Bob', 'Charlie', 'David','Eve']
})

# Pivot table
pivot_table = data.pivot_table(
    index='Name',
    values=['ID', 'Age'],
    aggfunc={'ID': 'mean', 'Age': 'mean'}
)

print(pivot_table)

          Age   ID
Name
Alice    20.0  1.0
Bob      25.0  2.0
Charlie  30.0  3.0
David    35.0  4.0
Eve      40.0  5.0

# 20.Cross Tab

In [52]:
import pandas as pd

# Sample data
data = pd.DataFrame({
    'Number_1': ['1', '1', '2', '2', '3', '1', '3'],
    'Alpha': ['X', 'Y', 'X', 'Y', 'Y', 'X', 'X']
})

# Crosstab with totals and normalized row-wise
cross_tab = pd.crosstab(
    data['Number_1'],
    data['Alpha'],
    margins=True,             
    normalize='index'          
)

print(cross_tab)

Alpha            X         Y
Number_1
1         0.666667  0.333333
2         0.500000  0.500000
3         0.500000  0.500000
All       0.571429  0.428571